spring:
  application:
    name: nollea-be
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  data:
    mongodb:
      uri: mongodb://nollea:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/nollea?authSource=admin
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
kakao:
  developers:
    app:
      api-key: ${KAKAO_MAP_API_KEY}